---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by feng.
--- DateTime: 2021/1/20 22:36
---

-- defines a factorial function
function fact(n)
    if n == 0 then
        return 1
    else
        return n * fact(n - 1)
    end
end

a = 42
print(fact(a))

--- 函数可以当成参数
local my_fact = fact
print(my_fact(5))

--- 多个返回值
function multi_return_value()
    return 1, 2, 3
end
i, j, k = multi_return_value()
print(i, j, k)

--- 可变参数
local function average(...)
    local result = 0
    local arg = { ... }
    for idx, val in ipairs(arg) do
        result = result + val;
    end
    return result / #arg, #arg
end
avg, num = average(1, 2, 3, 4, 5)
print(avg, num)