---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by feng.
--- DateTime: 2021/1/22 09:32
---

local i = 1
if i == 1 then
    print("i==1")
elseif i == 2 then
    print("i==2")
end

local i = 1
while i < 10 do
    print(i, "<10")
    if i == 5 then
        break
    end
    i = i + 1
end

for i = 1, 10 do
    print("i=", i)
end
