---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by feng.
--- DateTime: 2021/1/22 10:00
---

--- nil
local a = nil;
print(type(a))
--- number
local aNum = 10 / 3;
print(type(aNum))
--- string
local str = "Hello, World";
print(type(str))
local str2 = 'str2';
print(type(str2))
--- function
function aFunc()
end
print(type(aFunc))
--- boolean
--- Lua 把 false 和 nil 看作是 false，其他的都为 true，数字 0 也是 true
local aBoolean = true;
print(type(aBoolean))
--- table
local aTable = {}
print(type(aTable))

--- nil details
local aNil = nil
if aNil == nil then
    print("aNil is nil")
end
--- type() return string
print(type(type(aNonExistVar)))





