---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by feng.
--- DateTime: 2021/1/22 10:00
---

--- Lua 的数组以 1 开始
local tab1 = { "a", 3, 10 }
for k, v in pairs(tab1) do
    print(k .. ":" .. v)
end

local table1 = { key1 = "key1", key2 = "key2", "key3", 4, 5 }
for k, v in pairs(table1) do
    print(k .. "-" .. v)
end

table1.key1 = nil
for k, v in pairs(table1) do
    print(k .. "-" .. v)
end




