---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by feng.
--- DateTime: 2021/1/22 10:32
---

--- + 数字运算
--- 8.2
print("2" + "6.2")
print("2" + 6.2)

--- .. 字符串拼接
--- 26.2
print(2 .. 6.2)

--- # 计算长度
--- 11
print(#'Hello,World')


